CREATE DATABASE EdSquared_db;

CREATE TABLE ADMIN (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(50) UNIQUE,
  PASSWORD VARCHAR(255),
  CODE VARCHAR(6) NOT NULL,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE STUDENT (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  EMAIL VARCHAR(50) UNIQUE,
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(20) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ADMIN_STUDENTS (
  ADMIN_ID INT NOT NULL,
  STUDENT_ID INT NOT NULL,
  PRIMARY KEY (ADMIN_ID, STUDENT_ID),
  FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ID),
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID)
);

CREATE TABLE SUBJECTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL UNIQUE,
  COLOUR VARCHAR(10) NOT NULL
);

CREATE TABLE STUDENT_SUBJECTS (
  STUDENT_ID INT NOT NULL,
  SUBJECT_ID INT NOT NULL,
  PRIMARY KEY (STUDENT_ID, SUBJECT_ID),
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
  FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS(ID)
);

CREATE TABLE GRADES (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  EXAM_TYPE VARCHAR(40) NOT NULL,
  GRADE VARCHAR(4) NOT NULL,
  STUDENT_ID INT NOT NULL,
  SUBJECT_ID INT NOT NULL,
  ADDED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
  FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS(ID),
  UNIQUE (STUDENT_ID, SUBJECT_ID, ADDED_AT)
);

CREATE TABLE FEEDBACK (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  STUDENT_ID INT NOT NULL,
  SUBJECT_ID INT NOT NULL,
  FEEDBACK_TEXT TEXT NOT NULL,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
  FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS(ID),
  UNIQUE (ID, STUDENT_ID, SUBJECT_ID)
);

CREATE TABLE HOMEWORK (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  STUDENT_ID INT NOT NULL,
  HOMEWORK TEXT NOT NULL,
  STATUS BOOLEAN NOT NULL DEFAULT FALSE,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID)
);

CREATE TABLE LESSON_REPORT (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  STUDENT_ID INT NOT NULL,
  SUBJECT_ID INT NOT NULL,
  SUB_TOPIC VARCHAR(50) NOT NULL,
  LESSON_REPORT TEXT NOT NULL,
  LESSON_LINK TEXT NULL,
  CREATED_AT DATE NOT NULL,
  HOMEWORK_SET BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
  FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS(ID)
);
